services:

  backend:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: expert-booking-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    environment:
      - MONGO_URI=mongodb://mongo:27017/expert-booking

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - mongo

    restart: always

  mongo:
    image: mongo:latest
    container_name: expert-booking-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: